#!/bin/bash
set -euo pipefail

sudo apt update
sudo apt install -y \
ca-certificates \
cargo \
cmake \
cpu-checker \
cron \
distro-info \
dkms \
dmg2img \
fonts-arphic-ukai \
fonts-arphic-uming \
fonts-noto-cjk \
fonts-noto-cjk-extra \
fonts-noto-ui-core \
github-desktop \
gnome-calculator \
gnome-video-effects \
gnome-weather \
gnupg \
gparted \
htop \
ibus-chewing \
ibus-table-cangjie3 \
ibus-table-cangjie5 \
ibus-table-quick-classic \
ibus-table-wubi \
init \
inxi \
isc-dhcp-common \
krita \
kitty \
language-pack-zh-hans \
language-pack-zh-hant \
libconfig++9v5 \
libconfig++9v5:i386 \
libdbus-1-3:i386 \
libestr0 \
libfastjson4 \
libffado2 \
libffado2:i386 \
libfontconfig1-dev \
libgl1-mesa-dri:i386 \
libvulkan1:i386 \
libxcb-xfixes0-dev \
libxkbcommon-dev \
libxml++2.6-2v5 \
libxml++2.6-2v5:i386 \
libyaml-dev \
logrotate \
mesa-utils \
mesa-vulkan-drivers \
mesa-vulkan-drivers:i386 \
mokutil \
nautilus \
nautilus-sendto \
ncdu \
netcat-openbsd \
network-manager-pptp-gnome \
nmap \
p7zip-full \
piper \
plocate \
pop-desktop \
python3-pip \
ratbagd \
remmina \
rsyslog \
sessioninstaller \
software-properties-common \
stacer \
steam-installer \
system76-acpi-dkms \
system76-dkms \
system76-io-dkms \
timeshift \
tmux \
ubuntu-advantage-tools \
ubuntu-minimal \
ubuntu-standard \
uml-utilities \
vim-common \
vim-tiny \
wine \
wine32:i386 \
wine64 \
winetricks \
zsh \
xrdp 

# kraj